version: 2
accept_configuration:
  condition: property
  property: features
  not_contains_value: Disable

instructions:
  Build:
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test:
  - type: Group
    instructions:
      - !include "{{qt/qtbase}}/coin_module_test_template_v3.yaml"
    enable_if:
      condition: property
      property: host.os
      equals_value: Windows
  - type: EnvironmentVariable
    variableName: Dummy
    variableValue: dummy
    disable_if:
      condition: property
      property: host.os
      equals_value: Windows
